[package]
name = "seed-encoder"
version = "0.1.0"
edition = "2021"
description = "BIP-39 mnemonic seed phrase encoder for use with steel plates"
license = "Unlicense"

[dependencies]
once_cell = "1.18.0"
substring = "1.4.5"
thiserror = "1.0"
